'''add review runtime tables'''
revision = '6ec51be6e2eb'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_artifacts',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'artifact_id')
    )
    op.create_index(op.f('ix_model_artifacts_artifact_type'), 'model_artifacts', ['artifact_type'], unique=False)
    op.create_table('rule_confidence_states',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('runtime_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'rule_id', 'rule_version')
    )
    op.create_table('plan_snapshots',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('plan_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'source_artifact_id'], ['model_artifacts.client_id', 'model_artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'plan_id')
    )
    op.create_table('ontology_reviews',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('review_id', sa.String(length=128), nullable=False),
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('ontology_version', sa.String(length=64), nullable=False),
    sa.Column('overall_verdict', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'plan_id'], ['plan_snapshots.client_id', 'plan_snapshots.plan_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'review_id')
    )
    op.create_table('plan_decision_events',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'plan_id'], ['plan_snapshots.client_id', 'plan_snapshots.plan_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'decision_id')
    )
    op.create_table('plan_items',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('plan_item_id', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'plan_id'], ['plan_snapshots.client_id', 'plan_snapshots.plan_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'plan_id', 'plan_item_id')
    )
    op.create_table('ontology_review_items',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('review_id', sa.String(length=128), nullable=False),
    sa.Column('review_item_id', sa.String(length=128), nullable=False),
    sa.Column('plan_item_id', sa.String(length=128), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('confidence_snapshot', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'review_id'], ['ontology_reviews.client_id', 'ontology_reviews.review_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'review_id', 'review_item_id')
    )
    op.create_table('feedback_events',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_id', sa.String(length=128), nullable=False),
    sa.Column('review_id', sa.String(length=128), nullable=False),
    sa.Column('review_item_id', sa.String(length=128), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('event_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'review_id', 'review_item_id'], ['ontology_review_items.client_id', 'ontology_review_items.review_id', 'ontology_review_items.review_item_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'feedback_id')
    )
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Production migrations are forward-only')
